//! Experimental client for Codex's app-server JSON-RPC-over-JSONL protocol.
//!
//! This module deliberately owns the *wire* rather than the host process.  The
//! kernel's `EmbeddedKaish` is the single owner of host execution policy, so an
//! integration layer must provide a [`JsonlTransport`] after it has launched
//! `codex app-server --stdio` through that policy.  Keeping that boundary here
//! makes the protocol testable with an in-memory transport and prevents a
//! second, drifting `Command::new("codex")` path from appearing in the LLM
//! layer.
//!
//! The protocol is generated by the Codex binary and evolves quickly.  These
//! are intentionally small, locally-owned JSON shapes for the subset Kaijutsu
//! needs to experiment with: initialize, a new thread, one text turn, streamed
//! text/reasoning, completion, and safe default refusal of server requests.

use std::collections::VecDeque;
use std::io;

use async_trait::async_trait;
use serde_json::{Value, json};
use thiserror::Error;
use tokio::io::{AsyncBufReadExt, AsyncRead, AsyncWrite, AsyncWriteExt, BufReader};

use crate::llm::StreamEvent;

/// The version-neutral error surface for this experimental protocol bridge.
#[derive(Debug, Error)]
pub enum CodexError {
    #[error("Codex app-server transport: {0}")]
    Io(#[from] io::Error),
    #[error("Codex app-server sent invalid JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error("Codex app-server closed its JSONL stream")]
    Closed,
    #[error("Codex app-server protocol error: {0}")]
    Protocol(String),
    #[error("Codex app-server rejected {method}: {message}")]
    Rejected { method: String, message: String },
}

pub type Result<T> = std::result::Result<T, CodexError>;

/// Bidirectional line-delimited JSON transport for one app-server session.
///
/// A production implementation belongs beside the existing kaish-owned
/// external-exec plumbing.  It should launch `codex app-server --stdio`, pass
/// the child's pipes here, and own reaping that child when [`Self::close`] is
/// called.  There is deliberately no `Command::new` implementation in this
/// module.
#[async_trait]
pub trait JsonlTransport: Send {
    /// Receive one complete JSON object line. `None` means EOF.
    async fn receive(&mut self) -> Result<Option<Value>>;
    /// Send one complete JSON object line, flushing it for request ordering.
    async fn send(&mut self, value: Value) -> Result<()>;
    /// Close the underlying transport (and, for a process-backed transport,
    /// reap its child).  The app-server currently has no general shutdown RPC.
    async fn close(&mut self) -> Result<()>;
}

/// Standard-stream implementation of [`JsonlTransport`].
///
/// This is a codec, not a launcher.  Its input/output may be a child process's
/// stdout/stdin, a socket, or test duplex streams.
pub struct StdioJsonl<R, W> {
    reader: tokio::io::Lines<BufReader<R>>,
    writer: W,
}

impl<R, W> StdioJsonl<R, W>
where
    R: AsyncRead + Unpin,
    W: AsyncWrite + Unpin,
{
    pub fn new(reader: R, writer: W) -> Self {
        Self {
            reader: BufReader::new(reader).lines(),
            writer,
        }
    }
}

#[async_trait]
impl<R, W> JsonlTransport for StdioJsonl<R, W>
where
    R: AsyncRead + Send + Unpin,
    W: AsyncWrite + Send + Unpin,
{
    async fn receive(&mut self) -> Result<Option<Value>> {
        match self.reader.next_line().await? {
            Some(line) => Ok(Some(serde_json::from_str(&line)?)),
            None => Ok(None),
        }
    }

    async fn send(&mut self, value: Value) -> Result<()> {
        let encoded = serde_json::to_vec(&value)?;
        self.writer.write_all(&encoded).await?;
        self.writer.write_all(b"\n").await?;
        self.writer.flush().await?;
        Ok(())
    }

    async fn close(&mut self) -> Result<()> {
        self.writer.shutdown().await?;
        Ok(())
    }
}

/// A launch seam for the kaish/external-exec owner.
///
/// `LlmRegistry` wiring can depend on this trait without teaching the protocol
/// module anything about a host path, a working directory, or process policy.
#[async_trait]
pub trait AppServerLauncher: Send + Sync {
    type Transport: JsonlTransport;

    /// Start one `codex app-server --stdio` session under the caller's owned
    /// execution policy, returning a transport that also owns its lifecycle.
    async fn launch_codex_app_server(&self) -> Result<Self::Transport>;
}

/// Parameters used to begin a Codex thread.  Optional fields map directly to
/// the app-server v2 `thread/start` request, but intentionally exclude its
/// sprawling experimental surface.
#[derive(Debug, Clone, Default)]
pub struct ThreadStart {
    pub cwd: Option<String>,
    pub model: Option<String>,
    pub base_instructions: Option<String>,
    pub developer_instructions: Option<String>,
    /// Codex's app-server spelling: `read-only`, `workspace-write`, or
    /// `danger-full-access`.  Kaijutsu integrations should normally choose
    /// this from the loadout, not from model-controlled input.
    pub sandbox: Option<String>,
    /// Codex approval policy. Phase 0 pins this to `untrusted` instead of
    /// inheriting a possibly more permissive sidecar default.
    pub approval_policy: Option<String>,
}

/// Parameters used to begin a single text turn.
#[derive(Debug, Clone)]
pub struct TurnStart {
    pub thread_id: String,
    pub text: String,
    pub model: Option<String>,
    pub effort: Option<String>,
}

/// A single in-order app-server connection.
///
/// The protocol permits notifications and server requests while a client RPC
/// is outstanding.  Calls remain serialized here (as a model turn is), while
/// notifications are converted into Kaijutsu [`StreamEvent`]s and buffered.
pub struct Client<T> {
    transport: T,
    next_id: u64,
    pending: VecDeque<StreamEvent>,
    text_open: bool,
    thinking_open: bool,
}

impl<T: JsonlTransport> Client<T> {
    pub fn new(transport: T) -> Self {
        Self {
            transport,
            next_id: 1,
            pending: VecDeque::new(),
            text_open: false,
            thinking_open: false,
        }
    }

    /// Launch and complete the mandatory initialize/initialized handshake.
    pub async fn launch<L>(launcher: &L, client_name: &str, client_version: &str) -> Result<Self>
    where
        L: AppServerLauncher<Transport = T>,
    {
        let mut client = Self::new(launcher.launch_codex_app_server().await?);
        client.initialize(client_name, client_version).await?;
        Ok(client)
    }

    /// Negotiate the app-server session, then signal `initialized`.
    pub async fn initialize(&mut self, client_name: &str, client_version: &str) -> Result<Value> {
        let response = self
            .call(
                "initialize",
                json!({
                    "clientInfo": { "name": client_name, "version": client_version },
                    "capabilities": { "experimentalApi": false },
                }),
            )
            .await?;
        self.notify("initialized", Value::Null).await?;
        Ok(response)
    }

    /// Start a new Codex thread and return its app-server thread id.
    pub async fn start_thread(&mut self, start: ThreadStart) -> Result<String> {
        let mut params = json!({});
        if let Some(cwd) = start.cwd {
            params["cwd"] = Value::String(cwd);
        }
        if let Some(model) = start.model {
            params["model"] = Value::String(model);
        }
        if let Some(instructions) = start.base_instructions {
            params["baseInstructions"] = Value::String(instructions);
        }
        if let Some(instructions) = start.developer_instructions {
            params["developerInstructions"] = Value::String(instructions);
        }
        if let Some(sandbox) = start.sandbox {
            params["sandbox"] = Value::String(sandbox);
        }
        if let Some(approval_policy) = start.approval_policy {
            params["approvalPolicy"] = Value::String(approval_policy);
        }
        let response = self
            .call("thread/start", params)
            .await?;
        response
            .pointer("/thread/id")
            .and_then(Value::as_str)
            .map(str::to_owned)
            .ok_or_else(|| CodexError::Protocol("thread/start response omitted thread.id".into()))
    }

    /// Submit one text input item and return the app-server turn id.
    pub async fn start_turn(&mut self, start: TurnStart) -> Result<String> {
        let mut params = json!({
            "threadId": start.thread_id,
            "input": [{ "type": "text", "text": start.text }],
        });
        if let Some(model) = start.model {
            params["model"] = Value::String(model);
        }
        if let Some(effort) = start.effort {
            params["effort"] = Value::String(effort);
        }
        let response = self
            .call("turn/start", params)
            .await?;
        response
            .pointer("/turn/id")
            .and_then(Value::as_str)
            .map(str::to_owned)
            .ok_or_else(|| CodexError::Protocol("turn/start response omitted turn.id".into()))
    }

    /// Return the next translated stream event.  `None` means the app-server
    /// connection closed; normal end-of-turn is [`StreamEvent::Done`].
    pub async fn next_event(&mut self) -> Option<StreamEvent> {
        if let Some(event) = self.pending.pop_front() {
            return Some(event);
        }
        loop {
            let packet = match self.transport.receive().await {
                Ok(Some(packet)) => packet,
                Ok(None) => return None,
                Err(error) => return Some(StreamEvent::Error(error.to_string())),
            };
            match self.handle_packet(packet).await {
                Ok(()) => {
                    if let Some(event) = self.pending.pop_front() {
                        return Some(event);
                    }
                }
                Err(error) => return Some(StreamEvent::Error(error.to_string())),
            }
        }
    }

    /// Interrupt the named turn.  Codex confirms interruption through the
    /// usual `turn/completed` notification, which yields the terminal event.
    pub async fn interrupt_turn(&mut self, thread_id: &str, turn_id: &str) -> Result<()> {
        self.call("turn/interrupt", json!({ "threadId": thread_id, "turnId": turn_id }))
            .await?;
        Ok(())
    }

    /// Relinquish this connection.  A process-backed transport must also reap
    /// its child here, preserving the host-exec owner's lifecycle guarantee.
    pub async fn close(mut self) -> Result<()> {
        self.transport.close().await
    }

    async fn notify(&mut self, method: &str, params: Value) -> Result<()> {
        // app-server speaks JSON-RPC-shaped messages, but deliberately omits
        // the `jsonrpc` member (Codex's protocol README calls this out).
        let mut packet = json!({ "method": method });
        if !params.is_null() {
            packet["params"] = params;
        }
        self.transport.send(packet).await
    }

    async fn call(&mut self, method: &str, params: Value) -> Result<Value> {
        let id = self.next_id;
        self.next_id += 1;
        self.transport
            .send(json!({ "id": id, "method": method, "params": params }))
            .await?;

        loop {
            let packet = self.transport.receive().await?.ok_or(CodexError::Closed)?;
            if packet.get("id") == Some(&json!(id))
                && (packet.get("result").is_some() || packet.get("error").is_some())
            {
                if let Some(error) = packet.get("error") {
                    return Err(CodexError::Rejected {
                        method: method.to_owned(),
                        message: error
                            .get("message")
                            .and_then(Value::as_str)
                            .unwrap_or("unknown JSON-RPC error")
                            .to_owned(),
                    });
                }
                return Ok(packet.get("result").cloned().unwrap_or(Value::Null));
            }
            self.handle_packet(packet).await?;
        }
    }

    async fn handle_packet(&mut self, packet: Value) -> Result<()> {
        if packet.get("method").is_some() && packet.get("id").is_some() {
            return self.decline_server_request(packet).await;
        }
        let Some(method) = packet.get("method").and_then(Value::as_str) else {
            return Ok(()); // a response to a completed/unknown caller request
        };
        let params = packet.get("params").cloned().unwrap_or(Value::Null);
        self.translate_notification(method, &params);
        Ok(())
    }

    /// Decline every server request until Kaijutsu maps it through its own
    /// approval/loadout machinery.  Silently accepting here would give Codex a
    /// second execution authority, contradicting the kernel's kaish posture.
    async fn decline_server_request(&mut self, packet: Value) -> Result<()> {
        let id = packet
            .get("id")
            .cloned()
            .ok_or_else(|| CodexError::Protocol("server request without id".into()))?;
        let method = packet
            .get("method")
            .and_then(Value::as_str)
            .unwrap_or("unknown");
        let result = match method {
            "item/commandExecution/requestApproval" => json!({ "decision": "decline" }),
            "item/fileChange/requestApproval" => json!({ "decision": "decline" }),
            "applyPatchApproval" | "execCommandApproval" => json!({
                "decision": { "denied": { "rejection": "Kaijutsu Codex backend has no approval bridge yet" } }
            }),
            "item/tool/requestUserInput" => json!({ "answers": {} }),
            "mcpServer/elicitation/request" => json!({ "action": "decline", "content": null }),
            // This response type has no refusal variant.  A JSON-RPC error is
            // the only honest answer until permission projection is designed.
            "item/permissions/requestApproval" => {
                return self
                    .transport
                    .send(json!({
                        "id": id,
                        "error": { "code": -32001, "message": "Kaijutsu Codex backend declines permission changes" },
                    }))
                    .await;
            }
            _ => {
                return self
                    .transport
                    .send(json!({
                        "id": id,
                        "error": { "code": -32601, "message": "Kaijutsu does not implement this Codex server request" },
                    }))
                    .await;
            }
        };
        self.transport
            .send(json!({ "id": id, "result": result }))
            .await
    }

    fn translate_notification(&mut self, method: &str, params: &Value) {
        match method {
            "item/agentMessage/delta" => {
                if !self.text_open {
                    self.close_thinking();
                    self.pending.push_back(StreamEvent::TextStart);
                    self.text_open = true;
                }
                if let Some(delta) = params.get("delta").and_then(Value::as_str) {
                    self.pending.push_back(StreamEvent::TextDelta(delta.to_owned()));
                }
            }
            // Raw reasoning is deliberately not persisted. Codex exposes a
            // display-oriented summary stream separately; that is the honest
            // counterpart to Kaijutsu's thinking block.
            "item/reasoning/summaryTextDelta" => {
                if !self.thinking_open {
                    self.close_text();
                    self.pending.push_back(StreamEvent::ThinkingStart);
                    self.thinking_open = true;
                }
                if let Some(delta) = params.get("delta").and_then(Value::as_str) {
                    self.pending.push_back(StreamEvent::ThinkingDelta(delta.to_owned()));
                }
            }
            "turn/completed" => {
                self.close_open_blocks();
                let turn = params.get("turn").unwrap_or(params);
                let status = turn.get("status").and_then(Value::as_str);
                if status.is_some_and(|status| status != "completed") {
                    let detail = turn
                        .get("error")
                        .map(Value::to_string)
                        .unwrap_or_else(|| format!("Codex turn ended with status {status:?}"));
                    self.pending.push_back(StreamEvent::Error(detail));
                } else {
                    self.pending.push_back(StreamEvent::Done {
                        stop_reason: Some("end_turn".into()),
                        input_tokens: None,
                        output_tokens: None,
                        extra: None,
                    });
                }
            }
            "error" => {
                let detail = params
                    .get("error")
                    .or_else(|| params.get("message"))
                    .map(Value::to_string)
                    .unwrap_or_else(|| "Codex app-server reported an error".into());
                self.close_open_blocks();
                self.pending.push_back(StreamEvent::Error(detail));
            }
            _ => {}
        }
    }

    fn close_text(&mut self) {
        if self.text_open {
            self.pending.push_back(StreamEvent::TextEnd);
            self.text_open = false;
        }
    }

    fn close_thinking(&mut self) {
        if self.thinking_open {
            self.pending.push_back(StreamEvent::ThinkingEnd { signature: None });
            self.thinking_open = false;
        }
    }

    fn close_open_blocks(&mut self) {
        self.close_thinking();
        self.close_text();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct FakeTransport {
        incoming: VecDeque<Value>,
        sent: Vec<Value>,
    }

    impl FakeTransport {
        fn new(incoming: impl IntoIterator<Item = Value>) -> Self {
            Self { incoming: incoming.into_iter().collect(), sent: Vec::new() }
        }
    }

    #[async_trait]
    impl JsonlTransport for FakeTransport {
        async fn receive(&mut self) -> Result<Option<Value>> {
            Ok(self.incoming.pop_front())
        }
        async fn send(&mut self, value: Value) -> Result<()> {
            self.sent.push(value);
            Ok(())
        }
        async fn close(&mut self) -> Result<()> {
            Ok(())
        }
    }

    #[tokio::test]
    async fn handshake_starts_thread_and_turn_with_versioned_shapes() {
        let mut client = Client::new(FakeTransport::new([
            json!({ "id": 1, "result": { "userAgent": "codex" } }),
            json!({ "id": 2, "result": { "thread": { "id": "thread-1" } } }),
            json!({ "id": 3, "result": { "turn": { "id": "turn-1" } } }),
        ]));

        client.initialize("kaijutsu", "0.1").await.unwrap();
        assert_eq!(client.start_thread(ThreadStart::default()).await.unwrap(), "thread-1");
        assert_eq!(client.start_turn(TurnStart {
            thread_id: "thread-1".into(), text: "hello".into(), model: Some("gpt-5.6".into()), effort: None,
        }).await.unwrap(), "turn-1");

        let sent = &client.transport.sent;
        assert_eq!(sent[0]["method"], "initialize");
        assert!(sent[0].get("jsonrpc").is_none());
        assert_eq!(sent[1]["method"], "initialized");
        assert_eq!(sent[2]["method"], "thread/start");
        assert_eq!(sent[3]["method"], "turn/start");
        assert_eq!(sent[3]["params"]["input"][0], json!({ "type": "text", "text": "hello" }));
    }

    #[tokio::test]
    async fn interleaved_notifications_become_well_formed_stream_events() {
        let mut client = Client::new(FakeTransport::new([
            json!({ "method": "item/reasoning/summaryTextDelta", "params": { "delta": "consider" } }),
            json!({ "method": "item/agentMessage/delta", "params": { "delta": "answer" } }),
            json!({ "method": "turn/completed", "params": { "threadId": "t", "turn": { "status": "completed" } } }),
        ]));
        let mut events = Vec::new();
        while let Some(event) = client.next_event().await {
            let terminal = event.is_terminal();
            events.push(event);
            if terminal { break; }
        }
        assert_eq!(events, vec![
            StreamEvent::ThinkingStart,
            StreamEvent::ThinkingDelta("consider".into()),
            StreamEvent::ThinkingEnd { signature: None },
            StreamEvent::TextStart,
            StreamEvent::TextDelta("answer".into()),
            StreamEvent::TextEnd,
            StreamEvent::Done { stop_reason: Some("end_turn".into()), input_tokens: None, output_tokens: None, extra: None },
        ]);
    }

    #[tokio::test]
    async fn server_execution_request_is_declined_not_accepted() {
        let request = json!({
            "id": "approval-1",
            "method": "item/commandExecution/requestApproval", "params": {}
        });
        let mut client = Client::new(FakeTransport::new([request]));
        assert!(client.next_event().await.is_none());
        assert_eq!(client.transport.sent, vec![json!({
            "id": "approval-1", "result": { "decision": "decline" }
        })]);
    }

    #[tokio::test]
    async fn unknown_notifications_are_ignored_without_ending_the_turn() {
        let mut client = Client::new(FakeTransport::new([
            json!({ "method": "future/notification", "params": { "newField": true } }),
            json!({ "method": "item/agentMessage/delta", "params": { "delta": "still here" } }),
            json!({ "method": "turn/completed", "params": { "turn": { "status": "completed" } } }),
        ]));
        assert_eq!(client.next_event().await, Some(StreamEvent::TextStart));
        assert_eq!(client.next_event().await, Some(StreamEvent::TextDelta("still here".into())));
        assert_eq!(client.next_event().await, Some(StreamEvent::TextEnd));
        assert!(matches!(client.next_event().await, Some(StreamEvent::Done { .. })));
    }
}
